### ISSUE TITLE
Q&A example?

### ISSUE THREAD

**Issue by walking-octopus** [skeskinen/bert.cpp#3]
Forgive me for my ignorance, but I don't quite understand how BERT search and BERT Q&A differ. From what I can see, both using cosine similarity to find matching embedding, just trained on different datasets. If that is the case, would it mean that just taking [multi-qa-MiniLM-L6-cos-v1](https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1) model and converting it to GGML would just work without any changes? If so, can it be added to the list of downloadable models?

**Comment by skeskinen** [comment]
Yes, multi-qa-MiniLM-L6-cos-v1 looks like a finetune of MiniLM that should work out of the box with bert.cpp.
The only difference between 'multi-qa' model and 'all' model should be the training setup. Multi-qa has been trained to produce similar result vector for a question and the answer to that question.

If you load this model with sample client, you can see that when queried with a question, a sentence that vaguely looks like an answer will be closer than other questions:

python3 examples/sample_client.py 
Loading texts from sample_client_texts.txt...
Loaded 1738 lines.
Starting with a test query "Should I get health insurance?"
Closest texts:
1. On health care , the NDP says there will be no privatization and no health-care premiums .
 (similarity score: 0.4717)
2. Will my Medicare premiums be higher because of my higher income?
 (similarity score: 0.4335)
3. Can I sign up for Medicare Part B if I am working and have health insurance through an employer?
 (similarity score: 0.4064)
Enter a text to find similar texts (enter 'q' to quit):

I've added multi-qa-MiniLM-L6-cos-v1 to the downloadable models!


As a sidenote, some of the other "versions" might be a little different. E.g. it looks like the [paraphrase-multilingual-MiniLM-L12-v2](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2) has a different tokenizer setup, which would require some tuning to get working.
